version: '3.8'

services:

  fipe-postgres:
    image: postgres:15
    container_name: fipe-postgres
    restart: always
    environment:
      POSTGRES_DB: fipe_db
      POSTGRES_USER: fipe_user
      POSTGRES_PASSWORD: fipe_pass
    ports:
      - "5432:5432"
    volumes:
      - fipe_db-data:/var/lib/postgresql/data

  fipe-rabbitmq:
    image: rabbitmq:3-management
    container_name: fipe-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # user-interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  fipe-redis:
    image: redis:7
    container_name: fipe-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  fipe_db-data: