services:

  api1:
    build: ./api1
    container_name: api1
    ports:
      - "8080:8080"
    environment:
      # API2 communication
      API2_BASE_URL: http://api2:8080
      API2_INTERNAL_HEADER: X-Internal-Key
      API2_INTERNAL_KEY: b7f9c2a4-91d3-4f1a-8c7e-2d9a6b5c8e11

      # Redis
      REDIS_HOST: fipe-redis
      REDIS_PORT: 6379

      # RabbitMQ
      RABBITMQ_HOST: fipe-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

    depends_on:
      - api2
      - fipe-redis
      - fipe-rabbitmq

  api2:
    build: ./api2
    container_name: api2
    expose:
      - "8080"        # NOT exposed publicly
    environment:
      # Database
      DB_URL: jdbc:postgresql://fipe-postgres:5432/fipe_db
      DB_USERNAME: fipe_user
      DB_PASSWORD: fipe_pass

      # RabbitMQ
      RABBITMQ_HOST: fipe-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

      # Internal security
      INTERNAL_API_KEY: b7f9c2a4-91d3-4f1a-8c7e-2d9a6b5c8e11
      
      SERVER_PORT: 8080

    depends_on:
      - fipe-postgres
      - fipe-rabbitmq

  fipe-postgres:
    image: postgres:15
    container_name: fipe-postgres
    restart: always
    environment:
      POSTGRES_DB: fipe_db
      POSTGRES_USER: fipe_user
      POSTGRES_PASSWORD: fipe_pass
    ports:
      - "5432:5432"
    volumes:
      - fipe_db-data:/var/lib/postgresql/data

  fipe-rabbitmq:
    image: rabbitmq:3-management
    container_name: fipe-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" # user-interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  fipe-redis:
    image: redis:7
    container_name: fipe-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  fipe_db-data: