# NOTE:
# This configuration uses environment variables with default (fallback) values.
# You can run the project without setting any env vars.
# Override them only if you need custom environments (Docker, staging, prod, etc).

spring:
  application:
    name: api1

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

api2:
  base-url: ${API2_BASE_URL:http://localhost:8081}
  internal:
    header: ${API2_INTERNAL_HEADER:X-Internal-Key}
    key: ${API2_INTERNAL_KEY:b7f9c2a4-91d3-4f1a-8c7e-2d9a6b5c8e11}

server:
  port: ${SERVER_PORT:8080}

## Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
#    persistAuthorization: true
    tagsSorter: alpha

fipe-api:
  base-url: https://parallelum.com.br/fipe/api/v1
  ## Key to perform up to 1000 operations per day at FIPE API
  key: ${FIPE_API_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NzkzNmM2YS01NjU5LTQ1YzEtODFmZi02ODc4ZjdjNDhiMDMiLCJlbWFpbCI6InJvZHJpZ28ucnZzb3V6YUBnbWFpbC5jb20iLCJpYXQiOjE3NzQxNDU1MDB9.oxf8e6aEyVrUsAm1EL39GDiDz-KXJIZqBtipf6KQ798}
